#!/usr/bin/env python3
"""Assemble the GitHub Pages artifact for this repository.

The landing page is generated from ``docs/family/family-graph.json`` rather than
hand-written, so it cannot drift from what the repository actually contains. The
family explorer is installed at ``/family/``.
"""

from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
from pathlib import Path

# Generated file, rewritten whenever docs/family/ is regenerated. Edit the
# family-pages template rather than this copy; changes here do not survive.
TEMPLATE_ID = "vstd-family-pages/1"

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
FAMILY = DOCS / "family"
GRAPH = FAMILY / "family-graph.json"


class PagesBuildError(RuntimeError):
    pass


def install_family(output: Path) -> None:
    """Place the family explorer at <site>/family/ however docs were laid out."""
    dest = output / "family"
    if not dest.is_dir():
        if not FAMILY.is_dir():
            raise PagesBuildError(f"family explorer source missing: {FAMILY}")
        shutil.copytree(FAMILY, dest)
    if not (dest / "family-graph.json").is_file():
        raise PagesBuildError("family explorer is missing family-graph.json")


def load_node() -> dict:
    if not GRAPH.is_file():
        raise PagesBuildError(f"graph data missing: {GRAPH}")
    graph = json.loads(GRAPH.read_text(encoding="utf-8"))
    for node in graph["nodes"]:
        if node["id"] == ROOT.name:
            node["_graph"] = graph
            return node
    raise PagesBuildError(f"{ROOT.name} does not appear in {GRAPH.name}")


def link_list(items: list[tuple[str, str]]) -> str:
    if not items:
        return "<p class=\"none\">None.</p>"
    rows = "".join(
        f'<li><a href="{html.escape(href)}">{html.escape(label)}</a></li>'
        for label, href in items
    )
    return f"<ul>{rows}</ul>"


def render_index(node: dict) -> str:
    graph = node["_graph"]
    blob = (node["repo_url"] + "/blob/main/") if node["repo_url"] else ""
    counts = node["counts"]

    edges_out = [e for e in graph["edges"] if e["source"] == node["id"]]
    edges_in = [e for e in graph["edges"] if e["target"] == node["id"]]

    docs = [(p, blob + p) for p in (node.get("root_docs", []) + node["docs"])] if blob else []
    layers = [(p, blob + p) for p in node["layers"]] if blob else []
    papers = [(p, blob + p) for p in node["papers"]] if blob else []

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(node['id'])}</title>
<link rel="stylesheet" href="family/family.css">
<style>
  main {{ display: block; max-width: 820px; }}
  .lede {{ font-size: 17px; color: var(--muted); margin: 0 0 20px; }}
  .cta {{ display: inline-block; border: 1px solid var(--link); color: var(--link);
         border-radius: 6px; padding: 8px 14px; font-weight: 600; margin-bottom: 20px; }}
  .cta:hover {{ text-decoration: none; background: var(--panel); }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 16px; }}
  ul {{ padding-left: 20px; margin: 6px 0; }}
  li {{ font: 13px var(--mono); margin: 2px 0; }}
  .none {{ color: var(--faint); font-size: 13px; }}
  .stat {{ font-variant-numeric: tabular-nums; }}
</style>
</head>
<body data-focus="{html.escape(node['id'])}">
<header>
  <h1>{html.escape(node['id'])} <span class="sub">&middot; {html.escape(node['tier'])}</span></h1>
  <div class="spacer"></div>
  <span class="digest">graph {html.escape(graph['digest'][:12])}</span>
</header>
<main>
  <p class="lede">{html.escape(node['tagline'])}</p>
  <a class="cta" href="family/">Open the family explorer &rarr;</a>
  <p class="hint" style="margin-top:0">
    The explorer centres this repository in the hyper-* interaction graph and carries the
    combined API reference for every package in the family, searchable in one place.
  </p>
  <section>
    <h2>This repository</h2>
    <div class="facts">
      <span class="stat"><b>{counts['symbols']}</b> public symbols</span>
      <span class="stat"><b>{counts['modules']}</b> modules</span>
      <span class="stat"><b>{counts['layers']}</b> layer specifications</span>
      <span class="stat"><b>{len(edges_out)}</b> outgoing edges</span>
      <span class="stat"><b>{len(edges_in)}</b> incoming edges</span>
    </div>
    <div class="grid">
      <div><h2>Layer specifications</h2>{link_list(layers)}</div>
      <div><h2>Manuscript</h2>{link_list(papers)}</div>
      <div><h2>Documents</h2>{link_list(docs[:40])}</div>
    </div>
  </section>
  <p>Source: <a href="{html.escape(node['repo_url'] or '')}">{html.escape(node['repo_url'] or 'no public remote')}</a></p>
</main>
<footer>
  <p>Generated by <code>scripts/build_pages.py</code> from <code>docs/family/family-graph.json</code>.
  Nothing on this page is hand-maintained, so it cannot drift from the repository.</p>
</footer>
</body>
</html>
"""


def build(output: Path) -> Path:
    output = output.resolve()
    if output == ROOT:
        raise PagesBuildError("Pages output cannot be the repository root")
    if output.exists() and any(output.iterdir()):
        raise PagesBuildError(f"refusing to merge into non-empty Pages output: {output}")
    if output.exists():
        output.rmdir()
    output.mkdir(parents=True, exist_ok=True)

    node = load_node()
    install_family(output)
    (output / "index.html").write_text(render_index(node), encoding="utf-8")
    (output / ".nojekyll").write_text("", encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "_site")
    args = parser.parse_args(argv)
    try:
        out = build(args.output)
    except (OSError, PagesBuildError) as exc:
        print(f"[PAGES FAIL] {exc}", file=sys.stderr)
        return 1
    print(f"[PAGES OK] assembled documentation site at {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
